ARG ELIXIR_VERSION=1.18.1
ARG OTP_VERSION=27.2
ARG DEBIAN_VERSION=bullseye-20250113-slim

FROM hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}

ARG TARGETPLATFORM
ENV PHOENIX_VERSION=1.7.18

RUN apt-get update
RUN apt-get install -y make wget curl inotify-tools bash gcc libc-dev git locales-all

RUN rm -rf /var/lib/apt/lists/*\
  && apt-get purge --auto-remove\
  && apt-get clean

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
RUN touch ~/.bashrc

RUN mix local.hex --force
RUN mix local.rebar --force
RUN mix archive.install --force hex phx_new $PHOENIX_VERSION
